import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

abstract final class FleurIcons {
  const FleurIcons._();

  static const IconData feeds = LucideIcons.rss;
  static const IconData feedsSelected = LucideIcons.rss500;
  static const IconData saved = LucideIcons.bookmark;
  static const IconData savedSelected = LucideIcons.bookmark500;
  static const IconData search = LucideIcons.search;
  static const IconData searchSelected = LucideIcons.search500;
  static const IconData settings = LucideIcons.settings;
  static const IconData settingsSelected = LucideIcons.settings500;
  static const IconData back = LucideIcons.arrowLeft;
  static const IconData forward = LucideIcons.arrowRight;
  static const IconData sidebarCollapse = LucideIcons.panelLeftClose;
  static const IconData sidebarExpand = LucideIcons.panelLeftOpen;

  static const IconData translate = LucideIcons.languages;
  static const IconData fullText = LucideIcons.fileText;
  static const IconData refresh = LucideIcons.refreshCw;
  static const IconData markAllRead = LucideIcons.checkCheck;
  static const IconData filter = LucideIcons.funnel;
  static const IconData filterActive = LucideIcons.funnel500;
  static const IconData clear = LucideIcons.x;
  static const IconData close = LucideIcons.x;
  static const IconData article = LucideIcons.fileText;
  static const IconData brokenImage = LucideIcons.imageOff;
  static const IconData star = LucideIcons.star;
  static const IconData starActive = LucideIcons.star500;
  static const IconData markRead = LucideIcons.mailOpen;
  static const IconData markUnread = LucideIcons.mail;
  static const IconData openExternal = LucideIcons.externalLink;
  static const IconData moreHorizontal = LucideIcons.ellipsis;
  static const IconData readerSettings = LucideIcons.aLargeSmall;
  static const IconData aiSummary = LucideIcons.sparkles;
  static const IconData readLater = LucideIcons.clock;
  static const IconData readLaterActive = LucideIcons.clock500;
  static const IconData tag = LucideIcons.tag;
  static const IconData copy = LucideIcons.copy;
  static const IconData share = LucideIcons.share;
  static const IconData previousMatch = LucideIcons.chevronUp;
  static const IconData nextMatch = LucideIcons.chevronDown;
  static const IconData caseSensitive = LucideIcons.caseSensitive;
  static const IconData check = LucideIcons.check;
  static const IconData autoScroll = LucideIcons.chevronsUpDown;
  static const IconData statusOk = LucideIcons.check;
  static const IconData statusError = LucideIcons.circleAlert;
  static const IconData syncUpload = LucideIcons.cloudUpload;
  static const IconData syncWarning = LucideIcons.cloudAlert;
  static const IconData accountSwitcher = LucideIcons.chevronsUpDown;

  static const IconData allArticles = LucideIcons.inbox;
  static const IconData feed = LucideIcons.rss;
  static const IconData category = LucideIcons.folder;
  static const IconData categoryOpen = LucideIcons.folderOpen;
  static const IconData expand = LucideIcons.chevronRight;
  static const IconData collapse = LucideIcons.chevronDown;
  static const IconData moreVertical = LucideIcons.ellipsisVertical;
  static const IconData add = LucideIcons.plus;
  static const IconData addCategory = LucideIcons.folderPlus;
  static const IconData lock = LucideIcons.lock;
  static const IconData subscriptionDefaults = LucideIcons.slidersHorizontal;
  static const IconData rename = LucideIcons.pencil;
  static const IconData delete = LucideIcons.trash;
  static const IconData offlineCache = LucideIcons.download;
  static const IconData moveToCategory = LucideIcons.folderOpen;
  static const IconData importOpml = LucideIcons.upload;
  static const IconData exportOpml = LucideIcons.download;
  static const IconData chevronRight = LucideIcons.chevronRight;
  static const IconData dropdown = LucideIcons.chevronDown;
  static const IconData inherit = LucideIcons.rotateCcw;
  static const IconData reset = LucideIcons.rotateCcw;
  static const IconData localAccount = LucideIcons.rss;
  static const IconData minifluxAccount = LucideIcons.cloud;
  static const IconData feverAccount = LucideIcons.flame;
  static const IconData activeAccount = LucideIcons.circleCheck;
  static const IconData themeSystem = LucideIcons.monitor;
  static const IconData themeLight = LucideIcons.sun;
  static const IconData themeDark = LucideIcons.moon;
  static const IconData colorPicker = LucideIcons.pipette;
  static const IconData download = LucideIcons.download;
  static const IconData document = LucideIcons.fileText;

  static const IconData appPreferences = LucideIcons.settings;
  static const IconData appPreferencesSelected = LucideIcons.settings500;
  static const IconData grouping = LucideIcons.list;
  static const IconData groupingSelected = LucideIcons.list500;
  static const IconData services = LucideIcons.cloud;
  static const IconData servicesSelected = LucideIcons.cloud500;
  static const IconData translationAi = LucideIcons.languages;
  static const IconData translationAiSelected = LucideIcons.languages500;
  static const IconData about = LucideIcons.info;
  static const IconData aboutSelected = LucideIcons.info500;
  static const IconData aiChat = LucideIcons.messageCircle;
  static const IconData aiResponses = LucideIcons.zap;
  static const IconData aiGemini = LucideIcons.sparkles;
  static const IconData aiAnthropic = LucideIcons.brain;
  static const IconData language = LucideIcons.globe;
  static const IconData prompt = LucideIcons.notebookPen;
  static const IconData speed = LucideIcons.gauge;
}
