import 'package:flutter/widgets.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

abstract final class FleurIcons {
  const FleurIcons._();

  static const IconData feeds = PhosphorIconsRegular.newspaperClipping;
  static const IconData feedsSelected = PhosphorIconsBold.newspaperClipping;
  static const IconData saved = PhosphorIconsRegular.bookmarkSimple;
  static const IconData savedSelected = PhosphorIconsFill.bookmarkSimple;
  static const IconData search = PhosphorIconsRegular.magnifyingGlass;
  static const IconData searchSelected = PhosphorIconsBold.magnifyingGlass;
  static const IconData settings = PhosphorIconsRegular.gearSix;
  static const IconData settingsSelected = PhosphorIconsBold.gearSix;

  static const IconData translate = PhosphorIconsRegular.translate;
  static const IconData fullText = PhosphorIconsRegular.article;
  static const IconData refresh = PhosphorIconsRegular.arrowClockwise;
  static const IconData markAllRead = PhosphorIconsRegular.checks;
  static const IconData filter = PhosphorIconsRegular.funnelSimple;
  static const IconData filterActive = PhosphorIconsBold.funnelSimple;
  static const IconData clear = PhosphorIconsRegular.x;
  static const IconData close = PhosphorIconsRegular.x;
  static const IconData article = PhosphorIconsRegular.article;
  static const IconData brokenImage = PhosphorIconsRegular.imageBroken;
  static const IconData star = PhosphorIconsRegular.star;
  static const IconData starActive = PhosphorIconsFill.star;
  static const IconData markRead = PhosphorIconsRegular.envelopeSimpleOpen;
  static const IconData markUnread = PhosphorIconsRegular.envelopeSimple;
  static const IconData openExternal = PhosphorIconsRegular.arrowSquareOut;
  static const IconData moreHorizontal = PhosphorIconsRegular.dotsThree;
  static const IconData readerSettings = PhosphorIconsRegular.textT;
  static const IconData aiSummary = PhosphorIconsRegular.sparkle;
  static const IconData readLater = PhosphorIconsRegular.clockCountdown;
  static const IconData readLaterActive = PhosphorIconsFill.clockCountdown;
  static const IconData tag = PhosphorIconsRegular.tagSimple;
  static const IconData copy = PhosphorIconsRegular.copySimple;
  static const IconData share = PhosphorIconsRegular.share;
  static const IconData previousMatch = PhosphorIconsRegular.caretUp;
  static const IconData nextMatch = PhosphorIconsRegular.caretDown;
  static const IconData caseSensitive = PhosphorIconsRegular.textAa;
  static const IconData check = PhosphorIconsRegular.check;
  static const IconData autoScroll = PhosphorIconsRegular.caretUpDown;
  static const IconData statusOk = PhosphorIconsRegular.check;
  static const IconData statusError = PhosphorIconsRegular.warningCircle;
  static const IconData syncUpload = PhosphorIconsRegular.cloudArrowUp;
  static const IconData syncWarning = PhosphorIconsRegular.cloudWarning;
  static const IconData accountSwitcher = PhosphorIconsRegular.caretUpDown;

  static const IconData allArticles = PhosphorIconsRegular.tray;
  static const IconData feed = PhosphorIconsRegular.rssSimple;
  static const IconData category = PhosphorIconsRegular.folder;
  static const IconData categoryOpen = PhosphorIconsRegular.folderOpen;
  static const IconData expand = PhosphorIconsRegular.caretRight;
  static const IconData collapse = PhosphorIconsRegular.caretDown;
  static const IconData moreVertical = PhosphorIconsRegular.dotsThreeVertical;
  static const IconData add = PhosphorIconsRegular.plus;
  static const IconData addCategory = PhosphorIconsRegular.folderPlus;
  static const IconData lock = PhosphorIconsRegular.lockSimple;
  static const IconData subscriptionDefaults =
      PhosphorIconsRegular.slidersHorizontal;
  static const IconData rename = PhosphorIconsRegular.pencilSimple;
  static const IconData delete = PhosphorIconsRegular.trash;
  static const IconData offlineCache = PhosphorIconsRegular.downloadSimple;
  static const IconData moveToCategory = PhosphorIconsRegular.folderOpen;
  static const IconData importOpml = PhosphorIconsRegular.uploadSimple;
  static const IconData exportOpml = PhosphorIconsRegular.downloadSimple;
  static const IconData chevronRight = PhosphorIconsRegular.caretRight;
  static const IconData dropdown = PhosphorIconsRegular.caretDown;
  static const IconData inherit = PhosphorIconsRegular.arrowCounterClockwise;
  static const IconData reset = PhosphorIconsRegular.arrowCounterClockwise;
  static const IconData localAccount = PhosphorIconsRegular.rssSimple;
  static const IconData minifluxAccount = PhosphorIconsRegular.cloud;
  static const IconData feverAccount = PhosphorIconsRegular.flame;
  static const IconData activeAccount = PhosphorIconsRegular.checkCircle;
  static const IconData themeSystem = PhosphorIconsRegular.monitor;
  static const IconData themeLight = PhosphorIconsRegular.sun;
  static const IconData themeDark = PhosphorIconsRegular.moon;
  static const IconData colorPicker = PhosphorIconsRegular.eyedropper;
  static const IconData download = PhosphorIconsRegular.downloadSimple;
  static const IconData document = PhosphorIconsRegular.fileText;

  static const IconData appPreferences = PhosphorIconsRegular.gearSix;
  static const IconData appPreferencesSelected = PhosphorIconsBold.gearSix;
  static const IconData grouping = PhosphorIconsRegular.listBullets;
  static const IconData groupingSelected = PhosphorIconsBold.listBullets;
  static const IconData services = PhosphorIconsRegular.cloud;
  static const IconData servicesSelected = PhosphorIconsBold.cloud;
  static const IconData translationAi = PhosphorIconsRegular.translate;
  static const IconData translationAiSelected = PhosphorIconsBold.translate;
  static const IconData about = PhosphorIconsRegular.info;
  static const IconData aboutSelected = PhosphorIconsBold.info;
  static const IconData aiChat = PhosphorIconsRegular.chatCircle;
  static const IconData aiResponses = PhosphorIconsRegular.lightning;
  static const IconData aiGemini = PhosphorIconsRegular.sparkle;
  static const IconData aiAnthropic = PhosphorIconsRegular.brain;
  static const IconData language = PhosphorIconsRegular.globeHemisphereEast;
  static const IconData prompt = PhosphorIconsRegular.notePencil;
  static const IconData speed = PhosphorIconsRegular.speedometer;
}
