import 'package:flutter/widgets.dart';
import 'package:fluentui_system_icons/fluentui_system_icons.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

abstract final class FleurIcons {
  const FleurIcons._();

  static const IconData feeds = FluentIcons.rss_24_regular;
  static const IconData feedsSelected = FluentIcons.rss_24_filled;
  static const IconData saved = FluentIcons.bookmark_24_regular;
  static const IconData savedSelected = FluentIcons.bookmark_24_filled;
  static const IconData search = FluentIcons.search_24_regular;
  static const IconData searchSelected = FluentIcons.search_24_filled;
  static const IconData settings = FluentIcons.settings_24_regular;
  static const IconData settingsSelected = FluentIcons.settings_24_filled;

  static const IconData translate = PhosphorIconsRegular.translate;
  static const IconData fullText = FluentIcons.document_text_24_regular;
  static const IconData refresh = PhosphorIconsRegular.arrowClockwise;
  static const IconData markAllRead = PhosphorIconsRegular.checks;
  static const IconData filter = FluentIcons.filter_24_regular;
  static const IconData filterActive = FluentIcons.filter_24_filled;
  static const IconData clear = PhosphorIconsRegular.x;
  static const IconData close = PhosphorIconsRegular.x;
  static const IconData article = FluentIcons.document_text_24_regular;
  static const IconData brokenImage = PhosphorIconsRegular.imageBroken;
  static const IconData star = FluentIcons.star_24_regular;
  static const IconData starActive = FluentIcons.star_24_filled;
  static const IconData markRead = FluentIcons.mail_read_24_regular;
  static const IconData markUnread = FluentIcons.mail_unread_24_regular;
  static const IconData openExternal = PhosphorIconsRegular.arrowSquareOut;
  static const IconData moreHorizontal = PhosphorIconsRegular.dotsThree;
  static const IconData readerSettings = PhosphorIconsRegular.textT;
  static const IconData aiSummary = PhosphorIconsRegular.sparkle;
  static const IconData readLater = FluentIcons.clock_24_regular;
  static const IconData readLaterActive = FluentIcons.clock_24_filled;
  static const IconData tag = PhosphorIconsRegular.tagSimple;
  static const IconData copy = PhosphorIconsRegular.copySimple;
  static const IconData share = PhosphorIconsRegular.share;
  static const IconData previousMatch = PhosphorIconsRegular.caretUp;
  static const IconData nextMatch = PhosphorIconsRegular.caretDown;
  static const IconData caseSensitive = PhosphorIconsRegular.textAa;
  static const IconData check = PhosphorIconsRegular.check;
  static const IconData autoScroll = PhosphorIconsRegular.caretUpDown;
  static const IconData statusOk = PhosphorIconsRegular.check;
  static const IconData statusError = PhosphorIconsRegular.warningCircle;
  static const IconData syncUpload = PhosphorIconsRegular.cloudArrowUp;
  static const IconData syncWarning = PhosphorIconsRegular.cloudWarning;
  static const IconData accountSwitcher = PhosphorIconsRegular.caretUpDown;

  static const IconData allArticles = PhosphorIconsRegular.tray;
  static const IconData feed = FluentIcons.rss_24_regular;
  static const IconData category = FluentIcons.folder_24_regular;
  static const IconData categoryOpen = FluentIcons.folder_open_24_regular;
  static const IconData expand = PhosphorIconsRegular.caretRight;
  static const IconData collapse = PhosphorIconsRegular.caretDown;
  static const IconData moreVertical = PhosphorIconsRegular.dotsThreeVertical;
  static const IconData add = PhosphorIconsRegular.plus;
  static const IconData addCategory = PhosphorIconsRegular.folderPlus;
  static const IconData lock = PhosphorIconsRegular.lockSimple;
  static const IconData subscriptionDefaults =
      PhosphorIconsRegular.slidersHorizontal;
  static const IconData rename = PhosphorIconsRegular.pencilSimple;
  static const IconData delete = PhosphorIconsRegular.trash;
  static const IconData offlineCache = PhosphorIconsRegular.downloadSimple;
  static const IconData moveToCategory = PhosphorIconsRegular.folderOpen;
  static const IconData importOpml = PhosphorIconsRegular.uploadSimple;
  static const IconData exportOpml = PhosphorIconsRegular.downloadSimple;
  static const IconData chevronRight = PhosphorIconsRegular.caretRight;
  static const IconData dropdown = PhosphorIconsRegular.caretDown;
  static const IconData inherit = PhosphorIconsRegular.arrowCounterClockwise;
  static const IconData reset = PhosphorIconsRegular.arrowCounterClockwise;
  static const IconData localAccount = FluentIcons.rss_24_regular;
  static const IconData minifluxAccount = PhosphorIconsRegular.cloud;
  static const IconData feverAccount = PhosphorIconsRegular.flame;
  static const IconData activeAccount = PhosphorIconsRegular.checkCircle;
  static const IconData themeSystem = PhosphorIconsRegular.monitor;
  static const IconData themeLight = PhosphorIconsRegular.sun;
  static const IconData themeDark = PhosphorIconsRegular.moon;
  static const IconData colorPicker = PhosphorIconsRegular.eyedropper;
  static const IconData download = PhosphorIconsRegular.downloadSimple;
  static const IconData document = PhosphorIconsRegular.fileText;

  static const IconData appPreferences = FluentIcons.settings_24_regular;
  static const IconData appPreferencesSelected = FluentIcons.settings_24_filled;
  static const IconData grouping = FluentIcons.list_24_regular;
  static const IconData groupingSelected = FluentIcons.list_24_filled;
  static const IconData services = FluentIcons.cloud_24_regular;
  static const IconData servicesSelected = FluentIcons.cloud_24_filled;
  static const IconData translationAi = FluentIcons.translate_24_regular;
  static const IconData translationAiSelected = FluentIcons.translate_24_filled;
  static const IconData about = FluentIcons.info_24_regular;
  static const IconData aboutSelected = FluentIcons.info_24_filled;
  static const IconData aiChat = PhosphorIconsRegular.chatCircle;
  static const IconData aiResponses = PhosphorIconsRegular.lightning;
  static const IconData aiGemini = PhosphorIconsRegular.sparkle;
  static const IconData aiAnthropic = PhosphorIconsRegular.brain;
  static const IconData language = PhosphorIconsRegular.globeHemisphereEast;
  static const IconData prompt = PhosphorIconsRegular.notePencil;
  static const IconData speed = PhosphorIconsRegular.speedometer;
}
